apd2_upgrade_tables = {
  skills = { "player_intimidate_enemies", "player_primary_weapon_when_downed", "cable_tie", "player_steelsight_when_downed",
    "player_civ_harmless_melee", "player_silent_kill", "player_fall_health_damage_multiplier", "ecm_jammer_affects_cameras",
    "player_corpse_dispose", "trip_mine_sensor_toggle", "temporary_berserker_damage_multiplier_1", "player_cheat_death_chance_2",
    "weapon_automatic_head_shot_add_2", "player_regain_throwable_from_ammo_1", "player_headshot_regen_armor_bonus_1",
    "player_can_free_run", "player_run_and_reload", "player_detection_risk_damage_multiplier", "player_civ_harmless_bullets",
    "player_additional_lives_1", "player_additional_lives_2", "player_can_strafe_run", "player_run_and_shoot_1",
    "player_drill_melee_hit_restart_chance_1", "second_deployable_1", "player_shield_knock", "player_interacting_damage_multiplier",
    "snp_graze_damage_1", "snp_graze_damage_2", "head_shot_ammo_return_2" },

  perks = { "player_armor_health_store_amount_1", "player_armor_health_store_amount_2", "player_armor_health_store_amount_3",
    "player_armor_max_health_store_multiplier", "player_kill_change_regenerate_speed", "player_cocaine_stacking_1",
    "player_armor_grinding_1", "player_damage_to_armor_1", "player_damage_control_passive", "player_armor_to_health_conversion",
    "player_primary_reload_secondary_1", "player_secondary_reload_primary_1", "player_headshot_regen_health_bonus_1",
    "player_dodge_ricochet_bullets", "temporary_mrwi_health_invulnerable_1", "temporary_loose_ammo_restore_health_1",
    "temporary_loose_ammo_restore_health_2", "temporary_loose_ammo_restore_health_3", "melee_stacking_hit_damage_multiplier_1",
    "melee_stacking_hit_expire_t", "player_melee_life_leech", "player_melee_kill_life_leech", "player_killshot_regen_armor_bonus",
    "player_killshot_close_regen_armor_bonus", "player_killshot_close_panic_chance", "temporary_armor_break_invulnerable_1",
    "player_panic_suppression", "player_passive_health_regen" },

  stats = { "player_walk_speed_multiplier", "player_crouch_speed_multiplier", "first_aid_kit_deploy_time_multiplier",
    "first_aid_kit_quantity_increase_1", "player_revive_interaction_speed_multiplier", "cable_tie_quantity",
    "cable_tie_interact_speed_multiplier", "player_intimidate_range_mul", "player_civ_intimidation_mul",
    "player_stability_increase_bonus", "player_not_moving_accuracy_increase_bonus_1", "weapon_enter_steelsight_speed_multiplier",
    "player_steelsight_normal_movement_speed", "assault_rifle_zoom_increase", "snp_zoom_increase", "smg_zoom_increase",
    "pistol_zoom_increase", "assault_rifle_move_spread_index_addend", "snp_move_spread_index_addend", "weapon_single_spread_index_addend",
    "single_shot_accuracy_inc_1", "assault_rifle_reload_speed_multiplier", "smg_reload_speed_multiplier", "snp_reload_speed_multiplier",
    "shotgun_reload_speed_multiplier_1", "shotgun_reload_speed_multiplier_2", "shotgun_enter_steelsight_speed_multiplier",
    "shotgun_recoil_index_addend", "shotgun_damage_multiplier_1", "shotgun_damage_multiplier_2", "shotgun_steelsight_accuracy_inc_1",
    "shotgun_steelsight_range_inc_1", "shotgun_hip_rate_of_fire_1", "shotgun_magazine_capacity_inc_1", "weapon_swap_speed_multiplier",
    "player_armor_regen_time_mul_1", "player_flashbang_multiplier_1", "player_level_2_armor_addend", "player_level_3_armor_addend",
    "player_level_4_armor_addend", "carry_throw_distance_multiplier", "team_armor_regen_time_multiplier", "player_armor_multiplier",
    "player_increased_ammo_pickup_area_1", "player_hip_fire_accuracy_inc_1", "player_ap_bullets_1" },
}