apd2_upgrade_tables = {
  skills = {
    -- Default Upgrades
    "player_civ_harmless_melee",
    "player_intimidate_enemies",
    "player_primary_weapon_when_downed",
    "player_steelsight_when_downed",
    "player_silent_kill",
    "player_fall_health_damage_multiplier",
    "ecm_jammer_affects_cameras",
    "ecm_jammer_can_activate_feedback",
    "ecm_jammer_can_retrigger",
    "ecm_jammer_interaction_speed_multiplier",
    "player_corpse_dispose",
    "trip_mine_can_switch_on_off",
    "trip_mine_sensor_toggle", "trip_mine_sensor_highlight",
    "cable_tie",
    -- Mastermind Skills
    "temporary_revive_damage_reduction_1",
    "player_revive_damage_reduction_1",
    "first_aid_kit_deploy_time_multiplier",
    "first_aid_kit_damage_reduction_upgrade",
    "first_aid_kit_auto_recovery_1",
    "cooldown_long_dis_revive",
    "team_damage_hostage_absorption",
    "player_intimidate_aura",
    "player_civ_calming_alerts",
    "player_super_syndrome_1",
    "player_hostage_health_regen_addend_1", "player_hostage_health_regen_addend_2", 
    "temporary_single_shot_fast_reload_1",
    "head_shot_ammo_return_1", "head_shot_ammo_return_2",
    "snp_graze_damage_1", "snp_graze_damage_2",
    -- Enforcer Skills
    "player_damage_multiplier_outnumbered",
    "player_damage_dampener_outnumbered",
    "shotgun_hip_run_and_shoot_1",
    "player_overkill_damage_multiplier", "player_overkill_all_weapons",
    "player_interacting_damage_multiplier",
    "player_armor_carry_bonus_1",
    "player_shield_knock",
    "player_headshot_regen_armor_bonus_1", "player_headshot_regen_armor_bonus_2",
    "temporary_no_ammo_cost_1", "temporary_no_ammo_cost_2",
    "saw_ignore_shields_1",
    "saw_panic_when_kill_1",
    "player_regain_throwable_from_ammo_1",
    -- Technician Skills
    "sentry_gun_shield",
    "sentry_gun_ap_bullets",
    "second_deployable_1",
    "player_drill_alert",
    "player_silent_drill",
    "player_drill_autorepair_1",
    "player_drill_autorepair_2",
    "player_drill_melee_hit_restart_chance_1",
    "trip_mine_fire_trap_1", "trip_mine_fire_trap_2",
    "weapon_knock_down_1", "weapon_knock_down_2",
    "player_run_and_shoot_1",
    "player_automatic_faster_reload_1",
    "player_ap_bullets_1",
    "weapon_automatic_head_shot_add_1", "weapon_automatic_head_shot_add_2",
    -- Ghost Skills
    "player_sec_camera_highlight_mask_off",
    "player_special_enemy_highlight_mask_off",
    "player_mask_off_pickup",
    "player_small_loot_multiplier_1",
    "player_extra_corpse_dispose_amount",
    "player_standstill_omniscience",
    "player_additional_assets",
    "player_buy_bodybags_asset",
    "player_buy_spotter_asset",
    "player_tape_loop_duration_1", "player_tape_loop_duration_2",
    "player_pick_lock_hard",
    "ecm_jammer_can_open_sec_doors",
    "ecm_jammer_affects_pagers",
    "player_can_strafe_run", "player_can_free_run",
    "player_run_and_reload",
    "player_armor_depleted_stagger_shot_1", "player_armor_depleted_stagger_shot_2",
    "player_taser_malfunction",
    "player_taser_self_shock",
    "player_detection_risk_add_dodge_chance_1", "player_detection_risk_add_dodge_chance_2",
    "temporary_damage_speed_multiplier",
    "player_detection_risk_add_crit_chance_1", "player_detection_risk_add_crit_chance_2",
    "player_marked_enemy_extra_damage",
    "player_marked_inc_dmg_distance_1",
    "weapon_steelsight_highlight_specials",
    -- Fugitive Skills
    "pistol_stacked_accuracy_bonus_1",
    "pistol_stacking_hit_damage_multiplier_1", "pistol_stacking_hit_damage_multiplier_2",
    "player_temp_swap_weapon_faster_1",
    "player_temp_reload_weapon_faster_1",
    "player_temp_increased_movement_speed_1",
    "player_revived_damage_resist_1",
    "temporary_berserker_damage_multiplier_1", "temporary_berserker_damage_multiplier_2",
    "player_berserker_no_ammo_cost",
    "player_messiah_revive_from_bleed_out_1", "player_recharge_messiah_1",
    "player_cheat_death_chance_1", "player_cheat_death_chance_2",
    "player_melee_damage_stacking_1",
    "player_temp_melee_kill_increase_reload_speed_1",
    "player_counter_strike_melee",
    "player_counter_strike_spooc",
    "player_melee_damage_health_ratio_multiplier",
    "player_damage_health_ratio_multiplier",
    -- Unused
    "player_civ_harmless_bullets",
    "player_detection_risk_damage_multiplier"
  },

  perks = {
    -- Universal
    "weapon_passive_headshot_damage_multiplier",
    "player_passive_suspicion_bonus",
    "player_passive_armor_movement_penalty_multiplier",
    "passive_player_xp_multiplier",
    "weapon_passive_damage_multiplier",
    "passive_doctor_bag_interaction_speed_multiplier",
    "player_passive_loot_drop_multiplier",
    -- Crew Chief
    "team_damage_reduction_1",
    "player_passive_damage_reduction_1",
    "team_passive_stamina_multiplier_1",
    "player_passive_intimidate_range_mul",
    "team_passive_health_multiplier",
    "team_passive_armor_multiplier",
    "team_hostage_health_multiplier",
    "team_hostage_stamina_multiplier",
    "team_hostage_damage_dampener_multiplier",
    -- Muscle
    "player_passive_health_multiplier_1", "player_passive_health_multiplier_2", "player_passive_health_multiplier_3",
    "player_passive_health_multiplier_4", "player_passive_health_multiplier_5",
    "player_uncover_multiplier",
    "player_panic_suppression",
    "player_passive_health_regen",
    -- Armorer
    "player_tier_armor_multiplier_1", "player_tier_armor_multiplier_2", "player_tier_armor_multiplier_3",
    "player_tier_armor_multiplier_4", "player_tier_armor_multiplier_5", "player_tier_armor_multiplier_6",
    "player_armor_regen_timer_multiplier_passive",
    "temporary_armor_break_invulnerable_1",
    "team_passive_armor_regen_time_multiplier",
    -- Rogue
    "player_passive_dodge_chance_1", "player_passive_dodge_chance_2", "player_passive_dodge_chance_3",
    "player_camouflage_multiplier",
    "weapon_passive_armor_piercing_chance",
    "weapon_passive_swap_speed_multiplier_1",
    -- Hitman
    "player_perk_armor_regen_timer_multiplier_1", "player_perk_armor_regen_timer_multiplier_2",
    "player_perk_armor_regen_timer_multiplier_3", "player_perk_armor_regen_timer_multiplier_4",
    "player_perk_armor_regen_timer_multiplier_5",
    "player_passive_always_regen_armor_1",
    -- Crook
    "player_level_2_dodge_addend_1", "player_level_2_dodge_addend_2", "player_level_2_dodge_addend_3",
    "player_level_2_armor_multiplier_1", "player_level_2_armor_multiplier_2", "player_level_2_armor_multiplier_3",
    "player_level_3_dodge_addend_1", "player_level_3_dodge_addend_2", "player_level_3_dodge_addend_3",
    "player_level_3_armor_multiplier_1", "player_level_3_armor_multiplier_2", "player_level_3_armor_multiplier_3",
    "player_level_4_dodge_addend_1", "player_level_4_dodge_addend_2", "player_level_4_dodge_addend_3",
    "player_armor_regen_timer_multiplier_tier",
    -- Burglar
    "player_tier_dodge_chance_1", "player_tier_dodge_chance_2", "player_tier_dodge_chance_3",
    "player_stand_still_crouch_camouflage_bonus_1", "player_stand_still_crouch_camouflage_bonus_2",
    "player_stand_still_crouch_camouflage_bonus_3",
    "player_corpse_dispose_speed_multiplier",
    "player_pick_lock_speed_multiplier",
    "player_alarm_pager_speed_multiplier",
    "player_armor_regen_timer_stand_still_multiplier",
    -- Infiltrator
    "player_damage_dampener_outnumbered_strong",
    "player_damage_dampener_close_contact_1", "player_damage_dampener_close_contact_2", "player_damage_dampener_close_contact_3",
    "melee_stacking_hit_damage_multiplier_1",
    "melee_stacking_hit_expire_t",
    "player_melee_life_leech",
    -- Sociopath
    "player_killshot_regen_armor_bonus",
    "player_melee_kill_life_leech",
    "player_killshot_close_regen_armor_bonus",
    "player_killshot_close_panic_chance",
    -- Gambler
    "temporary_loose_ammo_restore_health_1", "temporary_loose_ammo_restore_health_2", "temporary_loose_ammo_restore_health_3",
    -- Grinder
    "player_damage_to_hot_1", "player_damage_to_hot_2", "player_damage_to_hot_3", "player_damage_to_hot_4",
    "player_armor_piercing_chance_1", "player_armor_piercing_chance_2",
    "player_damage_to_hot_extra_ticks",
    -- Yakuza
    "player_armor_regen_damage_health_ratio_multiplier_1", "player_armor_regen_damage_health_ratio_multiplier_2",
    "player_armor_regen_damage_health_ratio_multiplier_3",
    "player_movement_speed_damage_health_ratio_multiplier",
    "player_armor_regen_damage_health_ratio_threshold_multiplier",
    "player_movement_speed_damage_health_ratio_threshold_multiplier",
    -- Ex-Pres
    "player_armor_health_store_amount_1", "player_armor_health_store_amount_2", "player_armor_health_store_amount_3",
    "player_armor_max_health_store_multiplier",
    "player_kill_change_regenerate_speed",
    -- Maniac
    "player_cocaine_stacking_1",
    "player_cocaine_stacks_decay_multiplier_1",
    "player_sync_cocaine_upgrade_level_1",
    "player_cocaine_stack_absorption_multiplier_1",
    -- Anarchist
    "player_armor_grinding_1",
    "player_health_decrease_1",
    "player_armor_increase_1", "player_armor_increase_2", "player_armor_increase_3",
    "player_damage_to_armor_1",
    -- Biker
    "player_wild_health_amount_1",
    "player_wild_armor_amount_1",
    "player_less_health_wild_armor_1",
    "player_less_health_wild_cooldown_1",
    "player_less_armor_wild_health_1",
    "player_less_armor_wild_cooldown_1",
    -- Kingpin
    "chico_injector",
    "temporary_chico_injector_1",
    "player_chico_preferred_target",
    "player_chico_injector_low_health_multiplier",
    "player_chico_injector_health_to_speed",
    -- Sicario
    "smoke_screen_grenade",
    "player_dodge_shot_gain",
    "player_dodge_replenish_armor",
    "player_sicario_multiplier",
    -- Stoic
    "damage_control",
    "player_damage_control_passive",
    "player_damage_control_cooldown_drain_1", "player_damage_control_cooldown_drain_2",
    "player_armor_to_health_conversion",
    "player_damage_control_auto_shrug",
    "player_damage_control_healing",
    -- Tag Team
    "tag_team",
    "player_tag_team_base",
    "player_tag_team_cooldown_drain_1", "player_tag_team_cooldown_drain_2",
    "player_tag_team_damage_absorption",
    -- Hacker
    "pocket_ecm_jammer",
    "player_pocket_ecm_jammer_base",
    "player_pocket_ecm_heal_on_kill_1",
    "player_pocket_ecm_kill_dodge_1",
    -- Leech
    "copr_ability",
    "player_copr_static_damage_ratio_1", "player_copr_static_damage_ratio_2",
    "player_copr_kill_life_leech_1", "player_copr_kill_life_leech_2",
    "player_copr_activate_bonus_health_ratio_1",
    "player_copr_out_of_health_move_slow_1",
    "player_copr_speed_up_on_kill_1",
    "player_activate_ability_downed",
    -- Copycat
    "mrwi_health_multiplier_1", "mrwi_health_multiplier_2", "mrwi_health_multiplier_3", "mrwi_health_multiplier_4",
    "mrwi_armor_multiplier_1", "mrwi_armor_multiplier_2", "mrwi_armor_multiplier_3", "mrwi_armor_multiplier_4",
    "mrwi_dodge_chance_1", "mrwi_dodge_chance_2", "mrwi_dodge_chance_3", "mrwi_dodge_chance_4",
    "mrwi_crouch_speed_multiplier_1", "mrwi_crouch_speed_multiplier_2", "mrwi_crouch_speed_multiplier_3", "mrwi_crouch_speed_multiplier_4",
    "mrwi_carry_speed_multiplier_1", "mrwi_carry_speed_multiplier_2", "mrwi_carry_speed_multiplier_3", "mrwi_carry_speed_multiplier_4",
    "player_primary_reload_secondary_1",
    "player_secondary_reload_primary_1",
    "weapon_mrwi_swap_speed_multiplier_1",
    "player_headshot_regen_health_bonus_1",
    "player_dodge_ricochet_bullets",
    "temporary_mrwi_health_invulnerable_1"
  },

  stats = {
    -- Default Upgrades
    "player_walk_speed_multiplier",
    "player_crouch_speed_multiplier",
    "carry_interact_speed_multiplier_1", "carry_interact_speed_multiplier_2",
    "carry_movement_speed_multiplier",
    "player_fall_damage_multiplier",
    "player_corpse_dispose_amount_1", "player_corpse_dispose_amount_2",
    "striker_reload_speed_default",
    "akimbo_recoil_index_addend_1", "akimbo_recoil_index_addend_2", "akimbo_recoil_index_addend_3", "akimbo_recoil_index_addend_4",
    -- Mastermind Skills
    "first_aid_kit_quantity_increase_1", "first_aid_kit_quantity_increase_2",
    "doctor_bag_quantity", "doctor_bag_amount_increase1",
    "player_revive_interaction_speed_multiplier",
    "cable_tie_quantity", "cable_tie_interact_speed_multiplier",
    "player_intimidate_range_mul", "player_civ_intimidation_mul",
    "player_stability_increase_bonus_1",
    "player_not_moving_accuracy_increase_bonus_1",
    "weapon_enter_steelsight_speed_multiplier", "player_steelsight_normal_movement_speed",
    "lmg_zoom_increase", "assault_rifle_zoom_increase", "snp_zoom_increase", "smg_zoom_increase", "pistol_zoom_increase",
    "assault_rifle_move_spread_index_addend", "snp_move_spread_index_addend", "smg_move_spread_index_addend",
    "weapon_single_spread_index_addend", "single_shot_accuracy_inc_1",
    "assault_rifle_reload_speed_multiplier", "smg_reload_speed_multiplier", "snp_reload_speed_multiplier",
    -- Enforcer Skills
    "shotgun_reload_speed_multiplier_1", "shotgun_reload_speed_multiplier_2",
    "shotgun_enter_steelsight_speed_multiplier",
    "shotgun_recoil_index_addend",
    "shotgun_damage_multiplier_1", "shotgun_damage_multiplier_2",
    "shotgun_steelsight_accuracy_inc_1", "shotgun_steelsight_range_inc_1",
    "shotgun_hip_rate_of_fire_1",
    "shotgun_magazine_capacity_inc_1",
    "weapon_swap_speed_multiplier",
    "player_armor_regen_time_mul_1", "team_armor_regen_time_multiplier",
    "player_flashbang_multiplier_2",
    "player_level_2_armor_addend", "player_level_3_armor_addend", "player_level_4_armor_addend",
    "carry_throw_distance_multiplier",
    "player_armor_multiplier",
    "player_increased_pickup_area_1",
    "saw_extra_ammo_multiplier",
    "player_saw_speed_multiplier_1", "player_saw_speed_multiplier_2",
    "saw_lock_damage_multiplier_1", "saw_lock_damage_multiplier_2",
    "ammo_bag_quantity", "ammo_bag_ammo_increase1",
    "saw_enemy_slicer",
    "extra_ammo_multiplier1",
    "player_pick_up_ammo_multiplier", "player_pick_up_ammo_multiplier_2",
    -- Technician Skills
    "sentry_gun_cost_reduction_1", "sentry_gun_cost_reduction_2",
    "sentry_gun_spread_multiplier", "sentry_gun_rot_speed_multiplier",
    "sentry_gun_extra_ammo_multiplier_1", "sentry_gun_armor_multiplier",
    "deploy_interact_faster_1",
    "sentry_gun_quantity_1", "sentry_gun_quantity_2",
    "player_drill_fix_interaction_speed_multiplier",
    "player_trip_mine_deploy_time_multiplier", "player_trip_mine_deploy_time_multiplier_2",
    "trip_mine_explosion_size_multiplier_1", "trip_mine_explosion_size_multiplier_2",
    "trip_mine_damage_multiplier_1",
    "shape_charge_quantity_increase_1", "shape_charge_quantity_increase_2",
    "trip_mine_quantity_increase_1", "trip_mine_quantity_increase_2",
    "player_weapon_accuracy_increase_1",
    "player_stability_increase_bonus_2",
    "player_hip_fire_accuracy_inc_1",
    "player_weapon_movement_stability_1",
    "player_automatic_mag_increase_1",
    -- Ghost Skills
    "player_suspicion_bonus",
    "bodybags_bag_quantity",
    "player_cleaner_cost_multiplier",
    "player_pick_lock_easy_speed_multiplier",
    "ecm_jammer_duration_multiplier", "ecm_jammer_duration_multiplier_2",
    "ecm_jammer_feedback_duration_boost", "ecm_jammer_feedback_duration_boost_2",
    "ecm_jammer_quantity_increase_1", "ecm_jammer_quantity_increase_2",
    "player_stamina_regen_timer_multiplier", "player_stamina_regen_multiplier",
    "player_run_speed_multiplier",
    "player_run_dodge_chance",
    "player_movement_speed_multiplier",
    "player_climb_speed_multiplier_1",
    "player_climb_speed_multiplier_2",
    "player_melee_concealment_modifier",
    "player_ballistic_vest_concealment_1",
    "player_camouflage_bonus_1",
    "player_camouflage_bonus_2",
    "player_silencer_concealment_penalty_decrease_1",
    "player_silencer_concealment_increase_1",
    "weapon_silencer_recoil_index_addend",
    "weapon_silencer_enter_steelsight_speed_multiplier",
    "weapon_silencer_spread_index_addend",
    "player_mark_enemy_time_multiplier",
    -- Fugitive Skills
    "pistol_swap_speed_multiplier",
    "pistol_spread_index_addend",
    "pistol_magazine_capacity_inc_1",
    "pistol_fire_rate_multiplier",
    "akimbo_extra_ammo_multiplier_1", "akimbo_extra_ammo_multiplier_2",
    "pistol_damage_addend_1", "pistol_damage_addend_2",
    "pistol_reload_speed_multiplier",
    "player_bleed_out_health_multiplier",
    "player_additional_lives_1", "player_additional_lives_2",
    "player_revived_health_regain_1",
    "player_melee_damage_dampener",
    "player_melee_knockdown_mul",
    "player_non_special_melee_multiplier",
    "player_melee_damage_multiplier",
    "player_health_damage_reduction_1", "player_health_damage_reduction_2",
    -- Removed Skills
    "player_damage_shake_multiplier",
    "shotgun_hip_fire_spread_index_addend",
    "weapon_hip_fire_spread_index_addend",
    "weapon_clip_ammo_increase_1", "weapon_clip_ammo_increase_2",
    "smg_fire_rate_multiplier",
    "player_respawn_time_multiplier",
    "player_on_zipline_dodge_chance",
    "player_crouch_dodge_chance_1", "player_crouch_dodge_chance_2"
  },
}


-- UPGRADES NOT INCLUDED BECAUSE THEY HAVEN'T BEEN TESTED:
-- team_pistol_recoil_index_addend team_pistol_suppression_recoil_index_addend team_weapon_recoil_index_addend
-- team_weapon_suppression_recoil_index_addend


-- UPGRADES NOT INCLUDED BECAUSE THEY ONLY AFFECT MULTIPLAYER:
-- player_revive_health_boost player_revive_damage_reduction_level_1 player_revive_damage_reduction_level_2
-- player_morale_boost player_sync_cocaine_stacks team_pocket_ecm_heal_on_kill_1


-- UPGRADES NOT INCLUDED BECAUSE NEED TO REFACTOR CODE:

-- JOKERS:
-- player_convert_enemies player_convert_enemies_max_minions_1 player_convert_enemies_max_minions_2
-- player_convert_enemies_damage_multiplier_1 player_convert_enemies_damage_multiplier_2
-- player_convert_enemies_interaction_speed_multiplier
-- player_minion_master_speed_multiplier player_minion_master_health_multiplier
-- player_passive_convert_enemies_health_multiplier_1 player_passive_convert_enemies_health_multiplier_2

-- UNSEEN STRIKE:
-- player_unseen_increased_crit_chance_1 player_unseen_increased_crit_chance_2
-- player_unseen_temp_increased_crit_chance_1 player_unseen_temp_increased_crit_chance_2
